version: '3.7'

services:
  luckylibrary-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: luckylibrary-app
    ports:
      - "8090:8090"
    # networks:
    #   - backend
    depends_on:
      - luckylibrary-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://luckylibrary-db:3306/luckylibrary
      SPRING_DATASOURCE_USERNAME: <<YOUR DB USERNAME>>
      SPRING_DATASOURCE_PASSWORD: <<YOUR DB PASS>>

  luckylibrary-db:
    # image: "mcr.microsoft.com/mssql/server"
    # environment:
    #   SA_PASSWORD: "MS SQL ADMIN PASS"
    #   ACCEPT_EULA: "Y"
    # ports:
    #   - "1433:1433"
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: luckylibrary
      MYSQL_USER: <<YOUR DB USERNAME>>
      MYSQL_PASSWORD: <<YOUR DB PASS>>
      MYSQL_ROOT_PASSWORD: <<YOUR DB ROOT PASS>>
    volumes:
      - db-data:/var/lib/mysql
    # networks:
    #   - backend

volumes:
  db-data:

# networks:
#   backend: