version: '3.7'

services:
  luckylibrary-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: luckylibrary-app
    ports:
      - "8090:8090"
    # networks:
    #   - backend
    depends_on:
      - luckylibrary-db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  luckylibrary-db:
    image: mysql:8.0.18
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    # networks:
    #   - backend

volumes:
  db-data:

# networks:
#   backend: