server:
  port: 8090

spring:
  application:
    name: LuckyLibrary
  profiles:
    active: dev # Will be changed to prod when the app is in prod
  jpa:
    open-in-view: false

##### application-dev.yml #####
#spring:
#  application:
#    name: LuckyLibrary
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: DB URL
#    username: DB USERNAME
#    password: DB PASS
###############################