spring:
  application:
    name: LuckyLibrary
  profiles:
    active: dev # Will be changed to prod when the app is in prod
  jpa:
    open-in-view: false

##### application-dev.yml #####
#server:
#  port: 8090

###############################