server:
  port: 8090

spring:
  application:
    name: LuckyLibrary
  profiles:
    active: prod # dev for dev environment (application-dev.yml), and prod for procution
  jpa:
    open-in-view: false
