name: Docker Image CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DATASOURCE_URL }}
      DB_NAME: ${{ secrets.MYSQL_DATABASE }}
      DB_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      DB_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}

    steps:
    - uses: actions/checkout@v1
    - name: Bring DB online
      run: docker-compose -f ./docker-compose.db.yml up -d
    - name: Maven Build
      run: |
        mvn clean
        mvn package
    - name: Bring DB offline
      run: docker-compose -f ./docker-compose.db.yml down
    - name: Docker compose Build
      run: docker-compose build
    - name: Docker compose up
      run: docker-compose up -d
